# Dependencies
markdown:         CommonMark
highlighter:      rouge

# Permalinks
permalink:        none

# Setup
title:            Recipes
tagline:          'The meals we cook for each other @ Invo.'
description:      'The meals we cook for each other @ Invo.'
url:              http://recipes.goinvo.com
baseurl:          /

author:
  name:           'Involution Studios'
  url:            https://twitter.com/goinvo

# Custom vars
version:          0.1

github:
  repo:           https://github.com/goinvo/InvoRecipes

collections:
  recipes:
    output: true
    permalink: /recipes/:path/
